# ============================================================
# Portugal-Sim-Analysis.R
#
# Analysis of Monte Carlo simulation results for the graph supOU
# process, reproducing the figures of Section 4 of:
#
#   Mehta, S. and Veraart, A. E. D. (2026).
#   "Statistical inference for Lévy-driven graph supOU processes:
#    From short- to long-memory in high-dimensional time series."
#   arXiv:2502.08838 [stat.ME] (preprint).
#   https://arxiv.org/abs/2502.08838
#
# Must be run after Portugal-Sim.R has generated all 1000
# simulated datasets in the simdata/ subdirectory.
#
# Required input files (must be in the working directory):
#   adj_mat.csv                  -- 24x24 adjacency matrix for
#                                   the Portuguese subnetwork
#   simdata/POR_sim_data_i.txt   -- simulated datasets (i=1,...,1000)
#                                   generated by Portugal-Sim.R
#   GraphSupOU-Functions-Final.R -- defines find_max_eigen,
#                                   autocovariance, objective_function,
#                                   create_K, f, rmse,
#                                   median_absolute_error
#
# Output files (EPS):
#   sim_alpha.eps          -- boxplots of alpha-hat vs N*   (Figure 2a)
#   sim_c.eps              -- boxplots of c-hat vs N*       (Figure 2b)
#   sim-error.eps          -- RMSE and MAE vs N*            (Figure 2c)
#   p_vio.eps              -- violin plots at N*=40         (Figure 2d)
#   estmean_median_sim.eps -- median estimated Levy mean    (Figure 2e)
#   estvar_median_sim.eps  -- median estimated Levy var     (Figure 2f)
#   sim_pairs_contour.eps  -- (c-hat, alpha-hat) scatter plots (Figure 3)
#   sim_pairs_lag{N*}.eps  -- individual panels of Figure 3
#   sim_1step_results.rds  -- saved alpha_matrix and c_matrix
#   sim_1step_workspace.RData -- full workspace snapshot
#
# Sections:
#    1. Parallelised estimation of (alpha, c) for each MC run and lag
#    2. Extract parameter matrices
#    3. Boxplots of alpha and c estimates across lags (Figures 2a, 2b)
#    4. Error measures: RMSE and MAE vs lag (Figure 2c)
#    5. Violin plots at optimal lag N*=40 (Figure 2d)
#    6. Median heatmaps of estimated mean and variance (Figures 2e, 2f)
#    7. Scatter/density plots of (c-hat, alpha-hat) at selected lags (Figure 3)
#
# Dependencies: ggplot2, tidyr, reshape2, dplyr, patchwork,
#               parallel, doParallel, foreach
# Minimum requirements: R >= 4.1.0
# ============================================================

source("GraphSupOU-Functions-Final.R")

library(ggplot2)
library(tidyr)
library(reshape2)
library(dplyr)
library(patchwork)
library(parallel)
library(doParallel)
library(foreach)

# ── Setup ─────────────────────────────────────────────────────────────────────

Port_adjacency <- apply(as.matrix(read.csv(file = "adj_mat.csv")), 2, as.numeric)
A_norm         <- col_normalise_adjacency_matrix(Port_adjacency)

# True parameter values used in Portugal-Sim.R
MonteCarloNumber <- 1000
Delta            <- 1
true_alpha       <- 1.5
true_c           <- -0.8

# Common theme for all plots
my_theme <- theme(
  axis.title       = element_text(size = 30),
  axis.text        = element_text(size = 30),
  plot.title       = element_text(size = 30),
  legend.text      = element_text(size = 25),
  legend.title     = element_text(size = 25)
)

# Label mapping: columns correspond to N* = 5, 10, 15, ..., 100
# custom_labels() shows only multiples of 10 on the x-axis to avoid clutter
lag_vector      <- seq(5, 100, by = 5)
my_col          <- length(lag_vector)   # 20
original_labels <- paste0("V", seq(1, my_col))
label_map       <- setNames(lag_vector, original_labels)

custom_labels <- function(labels) {
  mapped <- as.integer(label_map[labels])
  ifelse(mapped %% 10 == 0, mapped, "")
}


# ── Section 1: Estimate (alpha, c) for each MC run and each lag ───────────────
# For each of the 1000 simulated datasets and each N* in lag_vector,
# minimise the Gamma supOU loss function (14) via L-BFGS-B with box
# constraints: c in (-1, 1), alpha in (1, 10).
# Eigenvalues up to lag 100 are computed once per run and sliced inside
# the inner loop — avoids redundant recomputation.
# Results are collected as lists and unpacked in Section 2.

n_cores <- detectCores() - 1
cat(paste("Using", n_cores, "cores\n"))
cl <- makeCluster(n_cores)
registerDoParallel(cl)

clusterExport(cl, varlist = c(
  "lag_vector", "my_col", "Delta",
  "find_max_eigen", "autocovariance",
  "objective_function"
))
clusterEvalQ(cl, library(expm))

my_parameter_list <- foreach(
  i              = 1:MonteCarloNumber,
  .packages      = "expm",
  .errorhandling = "pass"   # failed runs return an error object rather than aborting
) %dopar% {
  
  file_name <- paste0("simdata/POR_sim_data_", i, ".txt")
  X         <- as.matrix(read.table(file_name, header = FALSE, sep = "\t"))
  
  alpha_vector <- numeric(my_col)
  c_vector     <- numeric(my_col)
  
  # Compute all eigenvalues up to lag 100 once per run
  ev_all                   <- find_max_eigen(X, 100)
  max_real_eigenvalues_all <- ev_all$max_real_eigenvalues
  
  for (j in 1:my_col) {
    
    max_lag              <- lag_vector[j]
    max_real_eigenvalues <- max_real_eigenvalues_all[1:max_lag]
    h_values             <- (1:max_lag) * Delta
    
    fit <- optim(
      par      = c(0.5, 2),
      fn       = objective_function,
      h        = h_values,
      Delta    = Delta,
      observed = max_real_eigenvalues,
      method   = "L-BFGS-B",
      lower    = c(-0.9999, 1),
      upper    = c(0.9999, 10)
    )
    
    c_vector[j]     <- fit$par[1]
    alpha_vector[j] <- fit$par[2]
  }
  
  list(
    alpha_vector = alpha_vector,
    c_vector     = c_vector
  )
}

stopCluster(cl)

# Report any failed runs
failed <- which(sapply(my_parameter_list, inherits, "error"))
if (length(failed) > 0) {
  cat(paste("Warning: runs failed:", paste(failed, collapse = ", "), "\n"))
}
cat(paste("Completed", MonteCarloNumber - length(failed), "/",
          MonteCarloNumber, "MC runs\n"))


# ── Section 2: Extract parameter matrices ─────────────────────────────────────
# alpha_matrix: MonteCarloNumber x my_col matrix of alpha-hat estimates
# c_matrix:     MonteCarloNumber x my_col matrix of c-hat estimates
# Rows = MC runs, columns = values of N* in lag_vector.

alpha_matrix <- matrix(0, nrow = MonteCarloNumber, ncol = my_col)
c_matrix     <- matrix(0, nrow = MonteCarloNumber, ncol = my_col)

for (i in 1:MonteCarloNumber) {
  alpha_matrix[i, ] <- my_parameter_list[[i]]$alpha_vector
  c_matrix[i, ]     <- my_parameter_list[[i]]$c_vector
}

# Save results for potential downstream use
saveRDS(list(alpha_matrix = alpha_matrix, c_matrix = c_matrix),
        "sim_1step_results.rds")


# ── Section 3: Boxplots of alpha and c estimates across lags ──────────────────
# Figures 2a and 2b in the paper.
# Outliers are suppressed (outlier.shape = NA) for readability, as noted
# in the Figure 2 caption. The solid red line marks the true parameter value.

alpha_df   <- as.data.frame(alpha_matrix)
c_df       <- as.data.frame(c_matrix)

alpha_long <- melt(alpha_df, variable.name = "Column", value.name = "Alpha")
c_long     <- melt(c_df,     variable.name = "Column", value.name = "C")

alpha_long$Column <- as.factor(alpha_long$Column)
c_long$Column     <- as.factor(c_long$Column)

alpha_plot <- ggplot(alpha_long, aes(x = Column, y = Alpha)) +
  geom_boxplot(fill = "lightblue", outlier.shape = NA) +
  scale_x_discrete(labels = custom_labels) +
  labs(title = "", x = expression(N^"*"), y = expression(alpha)) +
  geom_hline(yintercept = true_alpha, color = "red") +
  my_theme

c_plot <- ggplot(c_long, aes(x = Column, y = C)) +
  geom_boxplot(fill = "lightgreen", outlier.shape = NA) +
  scale_x_discrete(labels = custom_labels) +
  labs(title = "", x = expression(N^"*"), y = "c") +
  geom_hline(yintercept = true_c, color = "red") +
  my_theme

ggsave("sim_alpha.eps", plot = alpha_plot, width = 20, height = 20, units = "cm")
ggsave("sim_c.eps",     plot = c_plot,     width = 20, height = 20, units = "cm")


# ── Section 4: Error measures — RMSE and MAE vs lag ──────────────────────────
# Figure 2c in the paper.
# Computes RMSE and MAE for both alpha-hat and c-hat across all MC runs
# at each value of N*, using rmse() and median_absolute_error() from
# GraphSupOU-Functions-Final.R.

error_data <- data.frame(
  lag        = lag_vector,
  med_alpha  = apply(alpha_matrix, 2, median_absolute_error, a = true_alpha),
  rmse_alpha = apply(alpha_matrix, 2, rmse,                   a = true_alpha),
  med_c      = apply(c_matrix,     2, median_absolute_error, a = true_c),
  rmse_c     = apply(c_matrix,     2, rmse,                   a = true_c)
)

error_long <- pivot_longer(error_data,
                           cols      = c(med_alpha, rmse_alpha, med_c, rmse_c),
                           names_to  = "variable",
                           values_to = "error")

p_error <- ggplot(error_long, aes(x = factor(lag), y = error,
                                  color = variable, group = variable)) +
  geom_line(linewidth = 0.5, linetype = "dotted") +
  geom_point(size = 3) +
  scale_x_discrete(labels = ifelse(lag_vector %% 10 == 0, lag_vector, "")) +
  scale_color_manual(
    values = c("med_alpha"  = "darkblue", "rmse_alpha" = "blue",
               "med_c"      = "darkgreen","rmse_c"     = "green"),
    labels = c(expression(MAE(alpha)), expression(MAE(c)),
               expression(RMSE(alpha)), expression(RMSE(c)))
  ) +
  labs(title = "", x = expression(N^"*"), y = "Error measure", color = "") +
  my_theme

ggsave("sim-error.eps", plot = p_error, width = 20, height = 20, units = "cm")


# ── Section 5: Violin plots at optimal lag N* = 40 ───────────────────────────
# Figure 2d in the paper.
# Shows the full distribution of (alpha-hat, c-hat) at N*=40, identified
# as the recommended lag in Section 4. Dashed lines mark true values.

opt_lag <- 40
opt_col <- which(lag_vector == opt_lag)

alpha_at_opt <- alpha_matrix[, opt_col]
c_at_opt     <- c_matrix[,     opt_col]

vio_data <- data.frame(
  value = c(alpha_at_opt, c_at_opt),
  group = rep(c("alpha", "c"), each = MonteCarloNumber)
)

p_vio <- ggplot(vio_data, aes(x = group, y = value, fill = group)) +
  geom_violin(trim = FALSE) +
  geom_hline(yintercept = true_alpha, color = "blue", linetype = "dashed") +
  geom_hline(yintercept = true_c,     color = "red",  linetype = "dashed") +
  scale_x_discrete(labels = c(expression(alpha), "c")) +
  scale_fill_manual(values = c("alpha" = "skyblue", "c" = "pink"),
                    labels = c(expression(alpha), "c")) +
  labs(title = "", x = "Parameter", y = "Value", fill = "") +
  my_theme

ggsave("p_vio.eps", plot = p_vio, width = 20, height = 20, units = "cm")


# ── Section 6: Median heatmaps of estimated mean and variance ─────────────────
# Figures 2e and 2f in the paper.
# For each MC run, estimates mu_L and sigma^2_L using the Step 2 formulas
# (equation (9), Proposition 3.2) at the optimal lag N*=40:
#   mu_hat  = (1 - alpha_i) * K_i %*% colMeans(X)
#   var_hat = (1 - alpha_i) * (K_i %*% cov(X) + cov(X) %*% t(K_i))
# Then takes the componentwise median across all 1000 runs.
# True values: mu_L = 0, sigma^2_L = 5*I_d.

my_mean_var_list <- vector("list", length = MonteCarloNumber)

for (i in 1:MonteCarloNumber) {
  
  c_i     <- c_matrix[i,     opt_col]
  alpha_i <- alpha_matrix[i, opt_col]
  K_i     <- create_K(c_i, A_norm)
  
  file_name <- paste0("simdata/POR_sim_data_", i, ".txt")
  X         <- as.matrix(read.table(file_name, header = FALSE, sep = "\t"))
  
  mu_hat  <- (1 - alpha_i) * K_i %*% as.numeric(colMeans(X))
  var_hat <- (1 - alpha_i) * (K_i %*% cov(X) + cov(X) %*% t(K_i))
  
  my_mean_var_list[[i]] <- list(mean = mu_hat, var = var_hat)
}

# Componentwise median over 1000 MC runs
median_var_matrix <- matrix(0, 24, 24)
median_mu_vec     <- numeric(24)

for (ii in 1:24) {
  for (jj in 1:24) {
    median_var_matrix[ii, jj] <- median(sapply(1:MonteCarloNumber,
                                               function(k) my_mean_var_list[[k]]$var[ii, jj]))
  }
  median_mu_vec[ii] <- median(sapply(1:MonteCarloNumber,
                                     function(k) my_mean_var_list[[k]]$mean[ii]))
}

# Figure 2f: median estimated variance heatmap
# Diagonal values are annotated directly on the plot
var_data           <- melt(median_var_matrix)
colnames(var_data) <- c("Row", "Column", "Value")
var_data$Row       <- factor(var_data$Row)
var_data$Column    <- factor(var_data$Column)

p_var <- ggplot(var_data, aes(x = Row, y = Column, fill = Value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red",
                       midpoint = 0, name = "Cov") +
  scale_x_discrete(breaks = seq(4, 24, by = 4), labels = as.character(seq(4, 24, by = 4))) +
  scale_y_discrete(breaks = paste0("X", seq(4, 24, by = 4)), labels = seq(4, 24, by = 4)) +
  geom_text(data = var_data %>% filter(as.numeric(as.character(Row)) == as.numeric(as.character(Column))),
            aes(label = round(Value, 2)), size = 5, color = "black") +
  labs(x = "Component", y = "Component") +
  my_theme

ggsave("estvar_median_sim.eps", plot = p_var, width = 20, height = 20, units = "cm")

# Figure 2e: median estimated mean bar chart (should be close to 0)
mean_data <- data.frame(Dimension = 1:24, Mean = median_mu_vec)

p_mean <- ggplot(mean_data, aes(x = Dimension, y = Mean, fill = Mean)) +
  geom_col() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red",
                       midpoint = 0, limits = c(-0.02, 0.02), name = "Mean") +
  labs(x = "Component", y = "Mean") +
  my_theme

ggsave("estmean_median_sim.eps", plot = p_mean, width = 20, height = 20, units = "cm")

save.image("sim_1step_workspace.RData")


# ── Section 7: Scatter/density plots of (c-hat, alpha-hat) at selected lags ───
# Figure 3 in the paper.
# For each N* in contour_lags, plots the joint distribution of (c-hat, alpha-hat)
# across all 1000 MC runs as a scatter plot with 2D density contours overlaid.
# The red cross marks the true value (c_0, alpha_0) = (-0.8, 1.5).
# Density contours are suppressed if the cloud is too degenerate (near-zero
# variance or fewer than 10 valid runs) to avoid kernel density failures.

contour_lags <- c(10, 30, 40, 50, 70, 100)
plot_list    <- vector("list", length(contour_lags))

for (k in seq_along(contour_lags)) {
  plot_list[[k]] <- local({
    lag_k <- contour_lags[k]
    col_k <- which(lag_vector == lag_k)
    
    c_vals     <- c_matrix[,     col_k]
    alpha_vals <- alpha_matrix[, col_k]
    keep       <- is.finite(c_vals) & is.finite(alpha_vals)
    c_vals     <- c_vals[keep]
    alpha_vals <- alpha_vals[keep]
    
    df <- data.frame(c_hat = c_vals, alpha_hat = alpha_vals)
    
    # Guard against degenerate clouds where kernel density estimation would fail
    can_density <- (sd(c_vals)     > 1e-6 &
                      sd(alpha_vals) > 1e-6 &
                      length(c_vals) >= 10)
    
    p <- ggplot() +
      geom_point(data = df, aes(x = c_hat, y = alpha_hat),
                 size = 0.8, color = "#5b9bd5") +
      geom_vline(xintercept = true_c,     color = "red", linetype = "dashed", linewidth = 0.4) +
      geom_hline(yintercept = true_alpha, color = "red", linetype = "dashed", linewidth = 0.4) +
      annotate("point", x = true_c, y = true_alpha,
               color = "red", size = 4, shape = 3, stroke = 2) +
      coord_cartesian(xlim = c(-1, 1), ylim = c(1, 10)) +
      labs(title = bquote(N^"*" == .(lag_k)), x = "c", y = expression(alpha)) +
      my_theme +
      theme(plot.title = element_text(size = 25, hjust = 0.5))
    
    if (can_density) {
      p <- p + geom_density_2d(data = df, aes(x = c_hat, y = alpha_hat),
                               color = "steelblue", linewidth = 0.7)
    }
    p
  })
}

# Combined 2x3 grid (Figure 3) and individual panels
p_pairs <- wrap_plots(plot_list, ncol = 3)
ggsave("sim_pairs_contour.eps", plot = p_pairs, width = 40, height = 30, units = "cm")

for (k in seq_along(contour_lags)) {
  ggsave(paste0("sim_pairs_lag", contour_lags[k], ".eps"),
         plot = plot_list[[k]], width = 20, height = 20, units = "cm")
}